import type { ComponentProps } from "react";
import type { ShaderGradient } from "@shadergradient/react";

type ShaderGradientProps = ComponentProps<typeof ShaderGradient> & {
  axesHelper?: string;
  bgColor1?: string;
  bgColor2?: string;
  destination?: string;
  embedMode?: string;
  format?: string;
  frameRate?: number;
  gizmoHelper?: string;
  pixelDensity?: number;
  fov?: number;
  range?: string;
  rangeEnd?: number;
  rangeStart?: number;
};

export interface GradientPreset {
  id: string;
  name: string;
  canvas: {
    pixelDensity: number;
    fov: number;
  };
  props: ShaderGradientProps;
}

export const GRADIENT_PRESETS: GradientPreset[] = [
  {
    id: "halo",
    name: "Halo",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#ff5005",
      color2: "#dbba95",
      color3: "#d0bce1",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: -1.4,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "plane",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "pensive",
    name: "Pensive",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.5,
      cAzimuthAngle: 250,
      cDistance: 1.5,
      cPolarAngle: 140,
      cameraZoom: 12.5,
      color1: "#809bd6",
      color2: "#910aff",
      color3: "#af38ff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.5,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 140,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 7,
      uDensity: 0.8,
      uFrequency: 5.5,
      uSpeed: 0.3,
      uStrength: 0.4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "mint",
    name: "Mint",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 170,
      cDistance: 4.4,
      cPolarAngle: 70,
      cameraZoom: 1,
      color1: "#94ffd1",
      color2: "#6bf5ff",
      color3: "#ffffff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 0.9,
      positionZ: -0.3,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 45,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1.2,
      uFrequency: 0,
      uSpeed: 0.2,
      uStrength: 3.4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "interstella",
    name: "interstella",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 0.8,
      cAzimuthAngle: 270,
      cDistance: 0.5,
      cPolarAngle: 180,
      cameraZoom: 15.1,
      color1: "#73bfc4",
      color2: "#ff810a",
      color3: "#8da0ce",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "env",
      positionX: -0.1,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.4,
      rotationX: 0,
      rotationY: 130,
      rotationZ: 70,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 3.2,
      uDensity: 0.8,
      uFrequency: 5.5,
      uSpeed: 0.3,
      uStrength: 0.3,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "nighty-night",
    name: "Nighty night",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1,
      cAzimuthAngle: 180,
      cDistance: 2.8,
      cPolarAngle: 80,
      cameraZoom: 9.1,
      color1: "#606080",
      color2: "#8d7dca",
      color3: "#212121",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 50,
      rotationY: 0,
      rotationZ: -60,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1.5,
      uFrequency: 0,
      uSpeed: 0.3,
      uStrength: 1.5,
      uTime: 8,
      wireframe: false,
    },
  },
  {
    id: "viola",
    name: "Viola",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "on",
      brightness: 1.1,
      cAzimuthAngle: 0,
      cDistance: 7.1,
      cPolarAngle: 140,
      cameraZoom: 17.3,
      color1: "#ffffff",
      color2: "#ffbb00",
      color3: "#0700ff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 1.4,
      uDensity: 1.1,
      uFrequency: 5.5,
      uSpeed: 0.1,
      uStrength: 1,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "universe",
    name: "Universe",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "on",
      brightness: 1.1,
      cAzimuthAngle: 180,
      cDistance: 3.9,
      cPolarAngle: 115,
      cameraZoom: 1,
      color1: "#5606ff",
      color2: "#fe8989",
      color3: "#000000",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: -0.5,
      positionY: 0.1,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 235,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1.1,
      uFrequency: 5.5,
      uSpeed: 0.1,
      uStrength: 2.4,
      uTime: 0.2,
      wireframe: false,
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "on",
      bgColor1: "#000000",
      bgColor2: "#000000",
      brightness: 1.5,
      cAzimuthAngle: 60,
      cDistance: 7.1,
      cPolarAngle: 90,
      cameraZoom: 15.3,
      color1: "#ff7a33",
      color2: "#33a0ff",
      color3: "#ffc53d",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "dawn",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: -0.15,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 1.4,
      uDensity: 1.1,
      uFrequency: 5.5,
      uSpeed: 0.1,
      uStrength: 0.4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "mandarin",
    name: "Mandarin",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "on",
      bgColor1: "#000000",
      bgColor2: "#000000",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 2.4,
      cPolarAngle: 95,
      cameraZoom: 1,
      color1: "#ff6a1a",
      color2: "#c73c00",
      color3: "#FD4912",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: -2.1,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 225,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1.8,
      uFrequency: 5.5,
      uSpeed: 0.2,
      uStrength: 3,
      uTime: 0.2,
      wireframe: false,
    },
  },
  {
    id: "cotton-candy",
    name: "Cotton Candy",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      bgColor1: "#000000",
      bgColor2: "#000000",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 2.9,
      cPolarAngle: 120,
      cameraZoom: 1,
      color1: "#ebedff",
      color2: "#f3f2f8",
      color3: "#dbf8ff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 1.8,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: -90,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1,
      uFrequency: 5.5,
      uSpeed: 0.3,
      uStrength: 3,
      uTime: 0.2,
      wireframe: false,
    },
  },
  {
    id: "orbit",
    name: "Orbit",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 5,
      color1: "#002683",
      color2: "#ab2eff",
      color3: "#f5feff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "solar",
    name: "Solar",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#d9d073",
      color2: "#fa4e19",
      color3: "#000000",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: -1.4,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "velvet",
    name: "Velvet",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#ffede5",
      color2: "#757bc2",
      color3: "#e0bddb",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: -1.4,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "plane",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1,
      cAzimuthAngle: 180,
      cDistance: 2.6,
      cPolarAngle: 90,
      cameraZoom: 8,
      color1: "#000000",
      color2: "#39355e",
      color3: "#d89eff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 90,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 3.1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.2,
      uStrength: 1,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "ember",
    name: "Ember",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 2.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#3c5454",
      color2: "#000000",
      color3: "#ff4f1b",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 30,
      rotationY: 0,
      rotationZ: 50,
      shader: "defaults",
      type: "plane",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 2,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "azure",
    name: "Azure",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.1,
      cAzimuthAngle: 0,
      cDistance: 12.6,
      cPolarAngle: 30,
      cameraZoom: 10.1,
      color1: "#d1ecff",
      color2: "#b7d6fb",
      color3: "#0700ff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0.3,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 5,
      uDensity: 1.1,
      uFrequency: 5.5,
      uSpeed: 0.1,
      uStrength: 1,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "tropical",
    name: "Tropical",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#ffbd80",
      color2: "#26c0fd",
      color3: "#ffb59e",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: -1.4,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "plane",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "sunlit",
    name: "Sunlit",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 2.9,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#fcbf78",
      color2: "#fcbf78",
      color3: "#94d5fa",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 0.5,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 45,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "plane",
      uAmplitude: 3.1,
      uDensity: 0.8,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 3.4,
      uTime: 0,
      wireframe: false,
    },
  },
];

// Helper function to generate a random color in hex format
function randomColor(): string {
  const r = Math.floor(Math.random() * 256);
  const g = Math.floor(Math.random() * 256);
  const b = Math.floor(Math.random() * 256);
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}

// Helper function to generate a random number in a range
function randomRange(min: number, max: number): number {
  return Math.random() * (max - min) + min;
}

// Helper function to generate a random integer in a range
function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

// Select a random preset from existing presets
export function getRandomPresetFromExisting(): GradientPreset {
  const randomIndex = randomInt(0, GRADIENT_PRESETS.length - 1);
  return GRADIENT_PRESETS[randomIndex];
}

// Generate a random gradient preset
export function generateRandomPreset(): GradientPreset {
  const types = ["plane", "sphere", "waterPlane"] as const;
  const envPresets = ["city", "dawn"] as const;
  const lightTypes = ["3d", "env"] as const;
  const grainOptions = ["on", "off"] as const;

  const type = types[randomInt(0, types.length - 1)];
  const envPreset = envPresets[randomInt(0, envPresets.length - 1)];
  const lightType = lightTypes[randomInt(0, lightTypes.length - 1)];
  const grain = grainOptions[randomInt(0, grainOptions.length - 1)];

  // Use safer ranges based on existing presets that avoid black areas
  // Most working presets use cDistance 2.6-3.9 and cameraZoom 1-9
  let cDistance: number;
  let cameraZoom: number;
  let cPolarAngle: number;
  let positionY: number;
  let cAzimuthAngle: number;

  // Adjust settings based on type to avoid black areas
  if (type === "sphere") {
    cDistance = randomRange(2.6, 3.9);
    cameraZoom = randomRange(1, 9);
    cPolarAngle = randomInt(80, 100);
    positionY = randomRange(0, 0.5);
    cAzimuthAngle = randomInt(170, 190); // Most sphere presets use 180
  } else if (type === "waterPlane") {
    cDistance = randomRange(2.6, 4.4);
    cameraZoom = randomRange(1, 9);
    cPolarAngle = randomInt(70, 95);
    positionY = randomRange(0, 1.0);
    cAzimuthAngle = randomInt(170, 190);
  } else {
    // plane
    cDistance = randomRange(2.6, 3.9);
    cameraZoom = randomRange(1, 9);
    cPolarAngle = randomInt(80, 100);
    positionY = randomRange(0, 0.5);
    cAzimuthAngle = randomInt(170, 190);
  }

  return {
    id: "random",
    name: "Random",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: randomRange(0.8, 1.5),
      cAzimuthAngle,
      cDistance,
      cPolarAngle,
      cameraZoom,
      color1: randomColor(),
      color2: randomColor(),
      color3: randomColor(),
      destination: "onCanvas",
      embedMode: "off",
      envPreset,
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain,
      lightType,
      positionX: randomRange(-1.4, 0.3),
      positionY,
      positionZ: randomRange(-0.3, 0),
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: randomRange(0.1, 0.5),
      rotationX: randomInt(0, 90),
      rotationY: randomInt(0, 180),
      rotationZ: randomInt(0, 180),
      shader: "defaults",
      type,
      uAmplitude: randomRange(0, 7),
      uDensity: randomRange(0.8, 2),
      uFrequency: randomRange(0, 5.5),
      uSpeed: randomRange(0.1, 0.8),
      uStrength: randomRange(0.4, 5),
      uTime: 0,
      wireframe: false,
    },
  };
}
