import type { ComponentProps } from "react";
import type { ShaderGradient } from "@shadergradient/react";

type ShaderGradientProps = ComponentProps<typeof ShaderGradient> & {
  axesHelper?: string;
  bgColor1?: string;
  bgColor2?: string;
  destination?: string;
  embedMode?: string;
  format?: string;
  frameRate?: number;
  gizmoHelper?: string;
  pixelDensity?: number;
  fov?: number;
  range?: string;
  rangeEnd?: number;
  rangeStart?: number;
};

export interface GradientPreset {
  id: string;
  name: string;
  canvas: {
    pixelDensity: number;
    fov: number;
  };
  props: ShaderGradientProps;
}

export const GRADIENT_PRESETS: GradientPreset[] = [
  {
    id: "halo",
    name: "Halo",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#ff5005",
      color2: "#dbba95",
      color3: "#d0bce1",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: -1.4,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "plane",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "pensive",
    name: "Pensive",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.5,
      cAzimuthAngle: 250,
      cDistance: 1.5,
      cPolarAngle: 140,
      cameraZoom: 12.5,
      color1: "#809bd6",
      color2: "#910aff",
      color3: "#af38ff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.5,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 140,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 7,
      uDensity: 0.8,
      uFrequency: 5.5,
      uSpeed: 0.3,
      uStrength: 0.4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "mint",
    name: "Mint",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 170,
      cDistance: 4.4,
      cPolarAngle: 70,
      cameraZoom: 1,
      color1: "#94ffd1",
      color2: "#6bf5ff",
      color3: "#ffffff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 0.9,
      positionZ: -0.3,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 45,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1.2,
      uFrequency: 0,
      uSpeed: 0.2,
      uStrength: 3.4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "interstella",
    name: "interstella",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 0.8,
      cAzimuthAngle: 270,
      cDistance: 0.5,
      cPolarAngle: 180,
      cameraZoom: 15.1,
      color1: "#73bfc4",
      color2: "#ff810a",
      color3: "#8da0ce",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "env",
      positionX: -0.1,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.4,
      rotationX: 0,
      rotationY: 130,
      rotationZ: 70,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 3.2,
      uDensity: 0.8,
      uFrequency: 5.5,
      uSpeed: 0.3,
      uStrength: 0.3,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "nighty-night",
    name: "Nighty night",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1,
      cAzimuthAngle: 180,
      cDistance: 2.8,
      cPolarAngle: 80,
      cameraZoom: 9.1,
      color1: "#606080",
      color2: "#8d7dca",
      color3: "#212121",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 50,
      rotationY: 0,
      rotationZ: -60,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1.5,
      uFrequency: 0,
      uSpeed: 0.3,
      uStrength: 1.5,
      uTime: 8,
      wireframe: false,
    },
  },
  {
    id: "viola",
    name: "Viola",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "on",
      brightness: 1.1,
      cAzimuthAngle: 0,
      cDistance: 7.1,
      cPolarAngle: 140,
      cameraZoom: 17.3,
      color1: "#ffffff",
      color2: "#ffbb00",
      color3: "#0700ff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 1.4,
      uDensity: 1.1,
      uFrequency: 5.5,
      uSpeed: 0.1,
      uStrength: 1,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "universe",
    name: "Universe",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "on",
      brightness: 1.1,
      cAzimuthAngle: 180,
      cDistance: 3.9,
      cPolarAngle: 115,
      cameraZoom: 1,
      color1: "#5606ff",
      color2: "#fe8989",
      color3: "#000000",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: -0.5,
      positionY: 0.1,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 235,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1.1,
      uFrequency: 5.5,
      uSpeed: 0.1,
      uStrength: 2.4,
      uTime: 0.2,
      wireframe: false,
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "on",
      bgColor1: "#000000",
      bgColor2: "#000000",
      brightness: 1.5,
      cAzimuthAngle: 60,
      cDistance: 7.1,
      cPolarAngle: 90,
      cameraZoom: 15.3,
      color1: "#ff7a33",
      color2: "#33a0ff",
      color3: "#ffc53d",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "dawn",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: -0.15,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 1.4,
      uDensity: 1.1,
      uFrequency: 5.5,
      uSpeed: 0.1,
      uStrength: 0.4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "mandarin",
    name: "Mandarin",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "on",
      bgColor1: "#000000",
      bgColor2: "#000000",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 2.4,
      cPolarAngle: 95,
      cameraZoom: 1,
      color1: "#ff6a1a",
      color2: "#c73c00",
      color3: "#FD4912",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: -2.1,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 225,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1.8,
      uFrequency: 5.5,
      uSpeed: 0.2,
      uStrength: 3,
      uTime: 0.2,
      wireframe: false,
    },
  },
  {
    id: "cotton-candy",
    name: "Cotton Candy",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      bgColor1: "#000000",
      bgColor2: "#000000",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 2.9,
      cPolarAngle: 120,
      cameraZoom: 1,
      color1: "#ebedff",
      color2: "#f3f2f8",
      color3: "#dbf8ff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: 0,
      positionY: 1.8,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 0,
      rotationZ: -90,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 0,
      uDensity: 1,
      uFrequency: 5.5,
      uSpeed: 0.3,
      uStrength: 3,
      uTime: 0.2,
      wireframe: false,
    },
  },
  {
    id: "deep-orbit",
    name: "Deep Orbit",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 5,
      color1: "#002683",
      color2: "#ab2eff",
      color3: "#f5feff",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "on",
      lightType: "3d",
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "sphere",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "solar-drift",
    name: "Solar Drift",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#d9d073",
      color2: "#fa4e19",
      color3: "#000000",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: -1.4,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "waterPlane",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
  {
    id: "velvet-dawn",
    name: "Velvet Dawn",
    canvas: { pixelDensity: 1, fov: 45 },
    props: {
      animate: "on",
      axesHelper: "off",
      brightness: 1.2,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      color1: "#ffede5",
      color2: "#757bc2",
      color3: "#e0bddb",
      destination: "onCanvas",
      embedMode: "off",
      envPreset: "city",
      format: "gif",
      frameRate: 10,
      gizmoHelper: "hide",
      grain: "off",
      lightType: "3d",
      positionX: -1.4,
      positionY: 0,
      positionZ: 0,
      range: "disabled",
      rangeEnd: 40,
      rangeStart: 0,
      reflection: 0.1,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      shader: "defaults",
      type: "plane",
      uAmplitude: 1,
      uDensity: 1.3,
      uFrequency: 5.5,
      uSpeed: 0.4,
      uStrength: 4,
      uTime: 0,
      wireframe: false,
    },
  },
];
